#!/bin/sh

#==============================================================================
# pir-repos-to-itp
# File ID: 932257d8-dc80-11ed-8b14-4f45262dc9b5
#
# [Description]
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=pir-repos-to-itp
VERSION=0.0.0

opt_help=0
opt_quiet=0
opt_real=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--real) opt_real=1; shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  --real
    This is for real. Actually run the commands, don't send them to 
    stdout.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

sim=$([ "$opt_real" = "1" ] || echo echo)

repos=$(cat <<END )
drywall
falkvinge-foredrag
pir-breddeprogram
pir-hordaland
pir-kjerneprogram
pir-medl
pir-norge
pir-politisk-program
pir-reboot
pir-rogaland
pir-tools
pir-valg
pir-valgprogram
pir-vedtekter
pir-wikikonv
piren
zenbership
END

$sim rm -rf repos
$sim mkdir repos
$sim cd repos || exit 1
for r in $repos; do
	$sim git clone -o gh-pir git@github.com:piratpartiet/$r.git \
	&& $sim cd $r \
	&& $sim git remote add gh-itp git@github.com:itpartiet/$r.git \
	&& $sim git remote add gl-itp git@gitlab.com:itpartiet/$r.git \
	&& $sim git remote add gl-pir git@gitlab.com:piratpartiet/$r.git \
	&& $sim git fetch --all --prune \
	&& $sim git checkout $(git log -1 --format=%H) \
	&& $sim bin/git-allbr -a -C \
	&& $sim git push --all gl-itp \
	&& $sim git push --tags gl-itp \
	&& $sim git push --all gh-itp \
	&& $sim git push --tags gh-itp \
	&& $sim cd .. \
	|| exit 1; \
done

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
